package uz.script.wincrm.utils;

public interface TableName {
    String USERS = "_users";
    String ROLES = "roles";
    String PERMISSIONS = "permissions";
    String REFRESH_TOKENS = "refresh_tokens";
    String AUDIT_LOGS = "audit_logs";
    String CLIENTS = "clients";
    String CLIENT_GROUPS="client_groups";
    String CLIENT_BALANCES="client_balances";
    String CLIENT_NOTES = "client_notes";
    String SUPPLIERS = "suppliers";
    String SUPPLIER_PAYMENTS= "supplier_payments";
    String SUPPLIER_BALANCE="supplier_BALANCE";
    String GOODS = "goods";
    String GOODS_GROUP = "goods_group";
    String UNIT_TYPES = "unit_types";
    String WAREHOUSE = "warehouse";
    String WAREHOUSE_ORDERS = "warehouse_order";
    String WAREHOUSE_ORDER_ITEMS = "warehouse_order_items";
    String INVENTORY_CHECKS = "inventory_checks";
    String INVENTORY_CHECK_ITEMS = "inventory_check_items";
    String SALE_ORDERS = "sale_orders";
    String SALE_ORDER_ITEMS = "sale_order_items";
    String SALE_ORDER_HISTORY = "sale_order_history";
    String SALE_ORDER_DISCOUNT_HISTORY = "sale_order_discount_history";
    String SALE_ORDER_WASTES = "sale_order_wastes";
    String SALE_ORDER_IMAGES = "sale_order_images";
    String STOCKS = "stocks";
    String STOCK_HISTORIES = "stock_histories";
    String STOCK_TRANSFERS = "stock_transfers";
    String PAYMENT_TYPES = "payment_types";
    String PAYMENTS = "payments";
    String PAYMENT_HISTORIES = "payment_histories";
    String SALARY_CONFIGS = "salary_configs";
    String SALARY_TRANSACTIONS = "salary_transactions";
    String EXPENSE = "expenses";
    String EXPENSE_CATEGORY = "expense_categories";
    String COMPANY_DETAIL = "company_detail";
    String DEBT_NOTIFICATION_HISTORY = "debt_notification_history";
    String TELEGRAM_USERS = "telegram_users";
    String BOT_SETTINGS   = "bot_settings";
}
